

UPDATE TestTable SET val = 1 WHERE id = 1;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

BEGIN TRANSACTION;  

SELECT val FROM TestTable WHERE id = 1;

UPDATE TestTable SET val = 3 WHERE id = 1;

WAITFOR DELAY '00:00:05';

COMMIT TRANSACTION;  

SELECT val FROM TestTable WHERE id = 1;