
UPDATE TestTable SET val = 2 WHERE id = 1;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION;  

SELECT val FROM TestTable;

WAITFOR DELAY '00:00:05';

SELECT val FROM TestTable;
UPDATE TestTable SET val = 3 WHERE id = 1;

WAITFOR DELAY '00:00:07';

SELECT val FROM TestTable;

COMMIT TRANSACTION;  
