SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION;  

SELECT val FROM TestTable;

WAITFOR DELAY '00:00:07';

SELECT val FROM TestTable;

COMMIT TRANSACTION;  

SELECT val FROM TestTable;